### ISSUE TITLE
Billing integration has been removed from Spree master

### ISSUE THREAD

**Issue by hughevans** [spree/spree_gateway#206]
Billing integration has been [removed from Spree master](https://github.com/spree/spree/pull/5934) so the [Skrill quick checkout](https://github.com/spree/spree_gateway/blob/master/app/models/spree/billing_integration/skrill/quick_checkout.rb) is broken, resulting in the following stack trace:

```
/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree_gateway-6b3479246b24/app/models/spree/billing_integration/skrill/quick_checkout.rb:2:in `<module:Spree>': superclass must be a Class (Module given) (TypeError)
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree_gateway-6b3479246b24/app/models/spree/billing_integration/skrill/quick_checkout.rb:1:in `<top (required)>'
```
For anyone working on master you can add this to `config/initializers/spree_billing_integration.rb` as a temporary workaround:

```ruby
module Spree
  class BillingIntegration < PaymentMethod
    validates :name, presence: true

    preference :server, :string, default: 'test'
    preference :test_mode, :boolean, default: true

    def provider
      integration_options = options
      ActiveMerchant::Billing::Base.integration_mode = integration_options[:server].to_sym
      integration_options[:test] = true if integration_options[:test_mode]
      @provider ||= provider_class.new(integration_options)
    end

    def options
      options_hash = {}
      preferences.each { |key, value| options_hash[key.to_sym] = value }
      options_hash
    end
  end
end
```

**Comment by hughevans** [comment]
:+1: thanks.
