### ISSUE TITLE
checkout/update/confirm error "something went wrong" Spree + Stripe Gateway

### ISSUE THREAD

**Issue by vike27** [spree/spree_gateway#217]
I believe I have followed all the steps correctly but I am getting an error on the checkout/update/confirm route after clicking the button "place order" on the preceding page.

I configured my Stripe gateway from my admin panel in the following manner:
1) Selected the Spree::Gateway::StripeGateway option from the provider drop-down selection 
2) Set my publishable & secret keys (test keys for fake cards) from Stripe
3) Typed in "live" in the Server field
4) Unpicked Test Mode Checkbox
5) Selected both in Display drop-down selection
6) Selected no on the autocapture drop-down selection
7) Picked Yes option in the Active radio button selection
8) Added a Name & Description
9) Updated my payment method sot that it saved the changes

The weird thing is that the charges are occurring because I can see them on my Stripe dashboard & the Spree orders dashboard afterwards. But for some reason Spree is throwing an error despite that.

Here is my Gemfile:

source 'https://rubygems.org'
ruby '2.1.5'

gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'rmagick', '2.14.0'
gem 'aws-sdk', '~> 1.61.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :production do
  gem 'pg'       
  gem 'rails_12factor'
end

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'spree', git: 'https://github.com/spree/spree.git', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'

Here is my Heroku logs --tail   

←[36m2015-04-07T07:29:38.013991+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:555:in `block (2 levels) in compile'
←[36m2015-04-07T07:29:38.013993+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:505:in `call'
←[36m2015-04-07T07:29:38.013994+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:505:in `call'
←[36m2015-04-07T07:29:38.013996+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:498:in `block (2 levels) in around'
←[36m2015-04-07T07:29:38.013998+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:343:in `call'
←[36m2015-04-07T07:29:38.014000+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:343:in `block (2 levels) in simple'
←[36m2015-04-07T07:29:38.014001+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activejob-4.2.1/lib/active_job/log
ging.rb:14:in `call'
←[36m2015-04-07T07:29:38.014003+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activejob-4.2.1/lib/active_job/log
ging.rb:14:in `block (3 levels) in <module:Logging>'
←[36m2015-04-07T07:29:38.014005+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activejob-4.2.1/lib/active_job/log
ging.rb:43:in `block in tag_logger'
←[36m2015-04-07T07:29:38.014007+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/tagged_logging.rb:68:in `block in tagged'
←[36m2015-04-07T07:29:38.014008+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/tagged_logging.rb:26:in `tagged'
←[36m2015-04-07T07:29:38.014010+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/tagged_logging.rb:68:in `tagged'
←[36m2015-04-07T07:29:38.014012+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activejob-4.2.1/lib/active_job/log
ging.rb:43:in `tag_logger'
←[36m2015-04-07T07:29:38.014014+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activejob-4.2.1/lib/active_job/log
ging.rb:13:in `block (2 levels) in <module:Logging>'
←[36m2015-04-07T07:29:38.014015+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:441:in `instance_exec'
←[36m2015-04-07T07:29:38.014017+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:441:in `block in make_lambda'
←[36m2015-04-07T07:29:38.014018+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:342:in `call'
←[36m2015-04-07T07:29:38.014020+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:342:in `block in simple'
←[36m2015-04-07T07:29:38.014040+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:497:in `call'
←[36m2015-04-07T07:29:38.014043+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:497:in `block in around'
←[36m2015-04-07T07:29:38.014044+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:505:in `call'
←[36m2015-04-07T07:29:38.014046+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:505:in `call'
←[36m2015-04-07T07:29:38.014077+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:92:in `_run_callbacks'
2015-04-07T07:29:38.014079+00:00 app[w
eb.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_enqueue_callback
s'
←[36m2015-04-07T07:29:38.014082+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:81:in `run_callbacks'
←[36m2015-04-07T07:29:38.014084+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activejob-4.2.1/lib/active_job/enq
ueuing.rb:67:in `enqueue'
←[36m2015-04-07T07:29:38.014086+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activejob-4.2.1/lib/active_job/con
figured_job.rb:13:in `perform_later'
←[36m2015-04-07T07:29:38.014087+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionmailer-4.2.1/lib/action_mail
er/message_delivery.rb:112:in `enqueue_delivery'
←[36m2015-04-07T07:29:38.014089+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionmailer-4.2.1/lib/action_mail
er/message_delivery.rb:68:in `deliver_later'
←[36m2015-04-07T07:29:38.014091+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/bundler/gems/spree-665c1c7a537c/core/ap
p/models/spree/order.rb:350:in `deliver_order_confirmation_email'
←[36m2015-04-07T07:29:38.014093+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/bundler/gems/spree-665c1c7a537c/core/ap
p/models/spree/order.rb:338:in `finalize!'
←[36m2015-04-07T07:29:38.014094+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/eval_helpers.rb:58:in `evaluate_method'
←[36m2015-04-07T07:29:38.014096+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/callback.rb:192:in `block in run_methods'
←[36m2015-04-07T07:29:38.014100+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/callback.rb:191:in `each'
←[36m2015-04-07T07:29:38.014102+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/callback.rb:191:in `run_methods'
←[36m2015-04-07T07:29:38.014103+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/callback.rb:159:in `call'
←[36m2015-04-07T07:29:38.014105+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:394:in `block (2 levels) in after'
←[36m2015-04-07T07:29:38.014107+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:394:in `each'
←[36m2015-04-07T07:29:38.014108+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:394:in `block in after'
←[36m2015-04-07T07:29:38.014110+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:392:in `catch'
←[36m2015-04-07T07:29:38.014111+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:392:in `after'
←[36m2015-04-07T07:29:38.014113+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:195:in `run_callbacks'
←[36m2015-04-07T07:29:38.014115+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition_collection.rb:127:in `run_callbacks'
←[36m2015-04-07T07:29:38.014116+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition_collection.rb:63:in `block (2 levels) in perform'
←[36m2015-04-07T07:29:38.014118+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition_collection.rb:63:in `catch'
←[36m2015-04-07T07:29:38.014120+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition_collection.rb:63:in `block in perform'
←[36m2015-04-07T07:29:38.014122+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition_collection.rb:182:in `block in within_transaction'
←[36m2015-04-07T07:29:38.014124+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:171:in `block in within_transaction'
←[36m2015-04-07T07:29:38.014131+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/machine.rb:1866:in `within_transaction'
←[36m2015-04-07T07:29:38.014133+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:170:in `within_transaction'
←[36m2015-04-07T07:29:38.014135+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition_collection.rb:181:in `within_transaction'
←[36m2015-04-07T07:29:38.014137+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition_collection.rb:62:in `perform'
←[36m2015-04-07T07:29:38.014138+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/transition.rb:163:in `perform'
←[36m2015-04-07T07:29:38.014140+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/event.rb:155:in `fire'
←[36m2015-04-07T07:29:38.014142+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/event.rb:219:in `block in add_actions'
←[36m2015-04-07T07:29:38.014143+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/machine.rb:725:in `call'
←[36m2015-04-07T07:29:38.014145+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/state_machines-0.2.2/lib/state_mac
hines/machine.rb:725:in `block (2 levels) in define_helper'
←[36m2015-04-07T07:29:38.014147+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/bundler/gems/spree-665c1c7a537c/fronten
d/app/controllers/spree/checkout_controller.rb:30:in `update'
←[36m2015-04-07T07:29:38.014153+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal/implicit_render.rb:4:in `send_action'
←[36m2015-04-07T07:29:38.014155+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/abstract_cont
roller/base.rb:198:in `process_action'
←[36m2015-04-07T07:29:38.014156+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal/rendering.rb:10:in `process_action'
←[36m2015-04-07T07:29:38.014158+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/abstract_cont
roller/callbacks.rb:20:in `block in process_action'
←[36m2015-04-07T07:29:38.014160+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:117:in `call'
←[36m2015-04-07T07:29:38.014161+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:117:in `call'
←[36m2015-04-07T07:29:38.014163+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:555:in `block (2 levels) in compile'
←[36m2015-04-07T07:29:38.014165+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:505:in `call'
←[36m2015-04-07T07:29:38.014167+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:505:in `call'
←[36m2015-04-07T07:29:38.014168+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:92:in `_run_callbacks'
←[36m2015-04-07T07:29:38.014170+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:776:in `_run_process_action_callbacks'
←[36m2015-04-07T07:29:38.014172+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:81:in `run_callbacks'
←[36m2015-04-07T07:29:38.014174+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/abstract_cont
roller/callbacks.rb:19:in `process_action'
←[36m2015-04-07T07:29:38.014175+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal/rescue.rb:29:in `process_action'
←[36m2015-04-07T07:29:38.014177+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal/instrumentation.rb:32:in `block in process_action'
←[36m2015-04-07T07:29:38.014179+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/notifications.rb:164:in `block in instrument'
←[36m2015-04-07T07:29:38.014181+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/notifications/instrumenter.rb:20:in `instrument'
←[36m2015-04-07T07:29:38.014183+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/notifications.rb:164:in `instrument'
←[36m2015-04-07T07:29:38.014185+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal/instrumentation.rb:30:in `process_action'
←[36m2015-04-07T07:29:38.014187+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal/params_wrapper.rb:250:in `process_action'
←[36m2015-04-07T07:29:38.014188+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_reco
rd/railties/controller_runtime.rb:18:in `process_action'
←[36m2015-04-07T07:29:38.014190+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/abstract_cont
roller/base.rb:137:in `process'
←[36m2015-04-07T07:29:38.014192+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionview-4.2.1/lib/action_view/r
endering.rb:30:in `process'
←[36m2015-04-07T07:29:38.014193+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal.rb:196:in `dispatch'
←[36m2015-04-07T07:29:38.014195+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal/rack_delegation.rb:13:in `dispatch'
←[36m2015-04-07T07:29:38.014197+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_contro
ller/metal.rb:237:in `block in action'
←[36m2015-04-07T07:29:38.014198+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/routing/route_set.rb:74:in `call'
←[36m2015-04-07T07:29:38.014200+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/routing/route_set.rb:74:in `dispatch'
←[36m2015-04-07T07:29:38.014202+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/routing/route_set.rb:43:in `serve'
←[36m2015-04-07T07:29:38.014203+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/journey/router.rb:43:in `block in serve'
←[36m2015-04-07T07:29:38.014205+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/journey/router.rb:30:in `each'
←[36m2015-04-07T07:29:38.014206+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/journey/router.rb:30:in `serve'
←[36m2015-04-07T07:29:38.014212+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/routing/route_set.rb:819:in `call'
←[36m2015-04-07T07:29:38.014214+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb
:518:in `call'
←[36m2015-04-07T07:29:38.014216+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/railtie.r
b:194:in `public_send'
←[36m2015-04-07T07:29:38.014217+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/railtie.r
b:194:in `method_missing'
←[36m2015-04-07T07:29:38.014219+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/routing/mapper.rb:51:in `serve'
←[36m2015-04-07T07:29:38.014221+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/journey/router.rb:43:in `block in serve'
←[36m2015-04-07T07:29:38.014226+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/journey/router.rb:30:in `each'
←[36m2015-04-07T07:29:38.014231+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/journey/router.rb:30:in `serve'
←[36m2015-04-07T07:29:38.014233+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/routing/route_set.rb:819:in `call'
←[36m2015-04-07T07:29:38.014235+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb
:35:in `block in call'
←[36m2015-04-07T07:29:38.014236+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb
:34:in `catch'
←[36m2015-04-07T07:29:38.014238+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb
:34:in `call'
←[36m2015-04-07T07:29:38.014240+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/etag.rb:24:in
`call'
←[36m2015-04-07T07:29:38.014242+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/conditionalget
.rb:38:in `call'
←[36m2015-04-07T07:29:38.014245+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in
`call'
←[36m2015-04-07T07:29:38.014247+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/params_parser.rb:27:in `call'
←[36m2015-04-07T07:29:38.014265+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/flash.rb:260:in `call'
←[36m2015-04-07T07:29:38.014268+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/session/abstra
ct/id.rb:225:in `context'
←[36m2015-04-07T07:29:38.014271+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/session/abstra
ct/id.rb:220:in `call'
←[36m2015-04-07T07:29:38.014273+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/cookies.rb:560:in `call'
←[36m2015-04-07T07:29:38.014276+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_reco
rd/query_cache.rb:36:in `call'
←[36m2015-04-07T07:29:38.014279+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_reco
rd/connection_adapters/abstract/connection_pool.rb:649:in `call'
←[36m2015-04-07T07:29:38.014281+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/callbacks.rb:29:in `block in call'
←[36m2015-04-07T07:29:38.014283+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:88:in `call'
←[36m2015-04-07T07:29:38.014286+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:88:in `_run_callbacks'
←[36m2015-04-07T07:29:38.014288+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:776:in `_run_call_callbacks'
←[36m2015-04-07T07:29:38.014290+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/callbacks.rb:81:in `run_callbacks'
←[36m2015-04-07T07:29:38.014292+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/callbacks.rb:27:in `call'
←[36m2015-04-07T07:29:38.014294+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/remote_ip.rb:78:in `call'
←[36m2015-04-07T07:29:38.014295+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/debug_exceptions.rb:17:in `call'
←[36m2015-04-07T07:29:38.014297+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/show_exceptions.rb:30:in `call'
←[36m2015-04-07T07:29:38.014299+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/rack/logg
er.rb:38:in `call_app'
←[36m2015-04-07T07:29:38.014300+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/rack/logg
er.rb:20:in `block in call'
←[36m2015-04-07T07:29:38.014302+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/tagged_logging.rb:68:in `block in tagged'
←[36m2015-04-07T07:29:38.014304+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/tagged_logging.rb:26:in `tagged'
←[36m2015-04-07T07:29:38.014306+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/tagged_logging.rb:68:in `tagged'
←[36m2015-04-07T07:29:38.014307+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/rack/logg
er.rb:20:in `call'
←[36m2015-04-07T07:29:38.014309+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/request_id.rb:21:in `call'
←[36m2015-04-07T07:29:38.014311+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride
.rb:22:in `call'
←[36m2015-04-07T07:29:38.014312+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:
in `call'
←[36m2015-04-07T07:29:38.014314+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_sup
port/cache/strategy/local_cache_mi
ddleware.rb:28:in `call'
←[36m2015-04-07T07:29:38.014316+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispat
ch/middleware/static.rb:113:in `call'
←[36m2015-04-07T07:29:38.014318+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/sendfile.rb:11
3:in `call'
←[36m2015-04-07T07:29:38.014320+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb
:518:in `call'
←[36m2015-04-07T07:29:38.014321+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/applicati
on.rb:164:in `call'
←[36m2015-04-07T07:29:38.014323+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/lock.rb:17:in
`call'
←[36m2015-04-07T07:29:38.014325+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/content_length
.rb:15:in `call'
←[36m2015-04-07T07:29:38.014326+00:00 app[web.1]:←[0m   vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/handler/webric
k.rb:89:in `service'
←[36m2015-04-07T07:29:38.014333+00:00 app[web.1]:←[0m   vendor/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `s
ervice'
←[36m2015-04-07T07:29:38.014335+00:00 app[web.1]:←[0m   vendor/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `ru
n'
←[36m2015-04-07T07:29:38.014337+00:00 app[web.1]:←[0m   vendor/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block
 in start_thread'
←[36m2015-04-07T07:29:38.014339+00:00 app[web.1]:←[0m
←[36m2015-04-07T07:29:38.014340+00:00 app[web.1]:←[0m
←[33m2015-04-07T07:29:38.018270+00:00 heroku[router]:←[0m at=info method=POST path="/checkout/update/confirm" host=www.u
salightingsystems.com request_id=34e56a15-b95e-42f3-a66d-719648bcd271 fwd="107.130.121.83" dyno=web.1 connect=1ms servic
e=1406ms status=500 bytes=1754

What could be happening, I don't see any error do you?

**Comment by vike27** [comment]
My mistake this should probably go in the main spree issue page, I am closing here as re-posting there.
