### ISSUE TITLE
Requires coffee_script but coffee-script is not a dependency

### ISSUE THREAD

**Issue by jalada** [spree/spree_gateway#224]
With `coffee-script` missing from the Gemfile:

```
/Users/jalada/.rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- coffee_script (LoadError)
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/bundler/gems/spree_gateway-fc1940d30748/lib/spree_gateway.rb:3:in `<top (required)>'
    from /Users/jalada/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.1/lib/bundler/runtime.rb:76:in `require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.1/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.1/lib/bundler/runtime.rb:72:in `each'
    from /Users/jalada/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.1/lib/bundler/runtime.rb:72:in `block in require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.1/lib/bundler/runtime.rb:61:in `each'
    from /Users/jalada/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.1/lib/bundler/runtime.rb:61:in `require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.1/lib/bundler.rb:134:in `require'
    from /Users/jalada/Development/xx-xx-x/config/application.rb:16:in `<top (required)>'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:82:in `require'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:82:in `preload'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
    from /Users/jalada/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/jalada/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/jalada/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

**Comment by JDutil** [comment]
Yea that's because coffee-script is being required:
https://github.com/spree/spree_gateway/blob/master/lib/spree_gateway.rb#L3

It should probably be moved to a runtime dependency instead of development or only required if it's bundled.

**Comment by michael-wise** [comment]
I encountered this issue today with the following gems. 

> source 'https://rubygems.org'
> gem 'rails', '~>4.2.6'
> gem 'therubyracer', platforms: :ruby
> gem 'spree', '~> 3.1.0'
> gem 'spree_auth_devise', '~> 3.1.0'
> gem 'spree_gateway', '~> 3.1.0'

I added the following to my gemfile just before spree (note that sass load failure had followed coffee load failure).

> gem 'coffee-rails'
> gem 'sass-rails'
